port:  4000
markdown: kramdown
name: Codeando Guadalajara
url: http://codeandoguadalajara.org
title: Codeando Guadalajara
description: "Comunidad de Hacking Cívico de Guadalajara"
encoding: utf-8
timezone: America/Chicago
gems:
  - jekyll-redirect-from
future: true